var express = require('express');
var app = express();
var router = express.Router();
var User = require('../modules/user.js');
var Books = require('../modules/book');
app.post('/api/user/login',User.checkLogin);
app.get('/api/log',User.isLogin);
app.get('/api/user/phone',User.checkPhone);
app.post('/api/user/register',User.createUser);
app.del('/api/user/logout',User.logout);
app.get('/api/book/autoComplete', Books.autoComplete);
app.get('/api/book/bookOnSale', Books.getOnSaleBooks);
app.get('/api/book/bookNew', Books.getNewBooks);
app.get('/api/book/bookInfo', Books.getBookInfo);
module.exports = app;
